### ISSUE TITLE
测试和几个问题

### ISSUE THREAD

**Issue by yllhwa** [XiaotianDong/safetree#2]
**经过测试，只要将代码中的shandong换成其他省份，qingdao换成其他市名即可使用**

但是源码中有几处存在问题：

1.__init__.py中:调用GetHomeWorkList()时，有一个地方将Student_Information拼写StudentInformation

2.__init__.py中:调用GetHomeWorkList()时，下标['CityCode']拼写为['CityCode]

3.__init__.py中:for homework in Homeworks:循环中 ["Name"] 和print的‘’拼写紊乱

4.API.py中:最后两行代码`
    `print(requests.get(URL,data).content.decode())`
    `return` demjson.decode(requests.get(URL,data).content.decode())
会报错，怀疑是因为decode()时，字符串中含有特殊符号所致。可以在使用decode的时候加上一个参数ignore，但是我直接注释掉了，因为调用时貌似并没有用到返回的参数。

我是刚刚开学python的小白,请多指教。

**Comment by XiaotianDong** [comment]
嗯，好的，我马上改，我其实也是个小白，有些代码规范没有遵守，给你带来困扰了，抱歉！
对于最后用demjson做处理，是因为他返回的json在最后有一个网址链接，在我用python原生的json库时需要使用re转换会导致URL被拆分，所以就直接用了demjson，然后用deconde()的原因很简单，我单纯只是为了把他的TrueName转换为中文，不然是unicode码，不方便阅读与后续处理，以便显示名称
